services:
  miner:
    image: ${DOCKER_IMAGE_NAME_WHATSAPP_MINER}
    container_name: ${DOCKER_CONTAINER_NAME_WHATSAPP_MINER}_miner_${ENV_NAME}
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    command: poetry run python src/receive_notification.py

  classifier:
    image: ${DOCKER_IMAGE_NAME_WHATSAPP_MINER}
    container_name: ${DOCKER_CONTAINER_NAME_WHATSAPP_MINER}_classifier_${ENV_NAME}
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    environment:
      - DATABASE_ENV=${ENV_NAME}
    entrypoint: ["/entrypoint_whatsapp_miner.sh"]

