#!/usr/bin/env bash
set -euo pipefail

# ── Load Doppler secrets
eval "$(doppler secrets download --no-file --format env)"

: "${AWS_EC2_HOST_ADDRESS:?}"
: "${AWS_EC2_USERNAME:?}"
: "${AWS_EC2_PEM_CHATBOT_SA_B64:?}"
: "${AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER:?}"
: "${DOCKER_IMAGE_NAME_WHATSAPP_MINER:?}"
: "${DOCKER_CONTAINER_NAME_WHATSAPP_MINER:?}"
: "${AWS_EC2_REGION:?}"
: "${AWS_IAM_WHATSAPP_MINER_ACCESS_KEY_ID:?}"
: "${AWS_IAM_WHATSAPP_MINER_ACCESS_KEY:?}"

# ── Generate login token
export AWS_ACCESS_KEY_ID="$AWS_IAM_WHATSAPP_MINER_ACCESS_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$AWS_IAM_WHATSAPP_MINER_ACCESS_KEY"
REGISTRY="${DOCKER_IMAGE_NAME_WHATSAPP_MINER%/*}"
LOGIN_PW=$(aws ecr get-login-password --region "$AWS_EC2_REGION")

# ── Prepare SSH key
KEY_FILE=$(mktemp)
echo "$AWS_EC2_PEM_CHATBOT_SA_B64" | base64 -d > "$KEY_FILE"
chmod 400 "$KEY_FILE"

# ── Run remote
ssh -i "$KEY_FILE" -o StrictHostKeyChecking=no "$AWS_EC2_USERNAME@$AWS_EC2_HOST_ADDRESS" bash -s <<EOF
set -euo pipefail
chmod +x "$AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER/docker_run_core.sh"
AWS_ECR_LOGIN_PASSWORD='$LOGIN_PW' \
AWS_ECR_REGISTRY='$REGISTRY' \
DOCKER_IMAGE_NAME_WHATSAPP_MINER='$DOCKER_IMAGE_NAME_WHATSAPP_MINER' \
DOCKER_CONTAINER_NAME_WHATSAPP_MINER='$DOCKER_CONTAINER_NAME_WHATSAPP_MINER' \
ENV_FILE='$AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER/whatsapp_miner.env' \
bash "$AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER/docker_run_core.sh"
EOF

rm "$KEY_FILE"
