services:
  whatsapp_sniffer:
    image: ${DOCKER_IMAGE_NAME_WHATSAPP_MINER}
    container_name: ${DOCKER_CONTAINER_NAME_WHATSAPP_MINER}_sniffer
    restart: unless-stopped
    command: poetry run python src/receive_notification.py
