name: Deploy Miner

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]

jobs:
  #───────────────────────────── decide dev|prd ──────────────────────────────
  env-name:
    runs-on: ubuntu-latest
    outputs:
      env: ${{ steps.pick.outputs.env }}
    steps:
      - id: pick
        run: |
          branch="${GITHUB_REF##*/}"
          [[ "$branch" == "main" ]] && echo "env=prd" >>"$GITHUB_OUTPUT" || echo "env=dev" >>"$GITHUB_OUTPUT"

  #──────────────────────── deployment ───────────────────────────────────────
  deploy:
    needs: env-name
    runs-on: ubuntu-latest
    environment: ${{ needs.env-name.outputs.env }}

    steps:
    # ── checkout ────────────────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ── create base-64 secret bundle ────────────────────────────────────────
    - name: Pack secrets into DEPLOY_ENV_B64
      id: pack
      shell: bash
      env:
        RAW_JSON: ${{ toJson(secrets) }}
      run: |
        b64=$(printf '%s' "$RAW_JSON" | base64 -w0)
        echo "::add-mask::$b64"      # mask value in logs
        echo "b64=$b64" >>"$GITHUB_OUTPUT"

    # ── set up Python tiny deps (for jq & scripts) ──────────────────────────
    - uses: actions/setup-python@v4
      with: { python-version: '3.11' }

    - run: sudo apt-get -qq update && sudo apt-get -qq install -y jq

    - name: Make scripts executable
      run: chmod +x docker_*.sh

    # ── run deployment script with blob flag ────────────────────────────────
    - name: Run deployment
      env: { CI: "true" }   # example extra flags if you need them
      run: |
        ./docker_deploy.sh \
            --env      "${{ needs.env-name.outputs.env }}" \
            --secrets-b64 "${{ steps.pack.outputs.b64 }}"
