name: Deploy Miner

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_EC2_HOST_ADDRESS: ${{ secrets.AWS_EC2_HOST_ADDRESS }}
      AWS_EC2_PEM_CHATBOT_SA_B64: ${{ secrets.AWS_EC2_PEM_CHATBOT_SA_B64 }}
      AWS_EC2_REGION: ${{ secrets.AWS_EC2_REGION }}
      AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME }}
      AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER: ${{ secrets.AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER }}
      AWS_IAM_WHATSAPP_MINER_ACCESS_KEY: ${{ secrets.AWS_IAM_WHATSAPP_MINER_ACCESS_KEY }}
      AWS_IAM_WHATSAPP_MINER_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_WHATSAPP_MINER_ACCESS_KEY_ID }}
      DOCKER_CONTAINER_NAME_WHATSAPP_MINER: ${{ secrets.DOCKER_CONTAINER_NAME_WHATSAPP_MINER }}
      DOCKER_IMAGE_NAME_WHATSAPP_MINER: ${{ secrets.DOCKER_IMAGE_NAME_WHATSAPP_MINER }}
      GREEN_API_INSTANCE_API_TOKEN: ${{ secrets.GREEN_API_INSTANCE_API_TOKEN }}
      GREEN_API_INSTANCE_ID: ${{ secrets.GREEN_API_INSTANCE_ID }}

    steps:
      - name: ✅ Check required secrets
        run: |
          missing=""
          for var in \
            AWS_EC2_HOST_ADDRESS \
            AWS_EC2_PEM_CHATBOT_SA_B64 \
            AWS_EC2_REGION \
            AWS_EC2_USERNAME \
            AWS_EC2_WORKING_DIRECTORY_WHATSAPP_MINER \
            AWS_IAM_WHATSAPP_MINER_ACCESS_KEY \
            AWS_IAM_WHATSAPP_MINER_ACCESS_KEY_ID \
            DOCKER_CONTAINER_NAME_WHATSAPP_MINER \
            DOCKER_IMAGE_NAME_WHATSAPP_MINER \
            GREEN_API_INSTANCE_API_TOKEN \
            GREEN_API_INSTANCE_ID
          do
            if [[ -z "${!var:-}" ]]; then
              echo "❌ Missing: $var"
              missing=1
            fi
          done
          if [[ -n "$missing" ]]; then
            echo "❌ One or more required secrets are missing. Aborting."
            exit 1
          else
            echo "✅ All required secrets are present."
          fi

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Decode PEM key
        run: |
          echo "$AWS_EC2_PEM_CHATBOT_SA_B64" | base64 -d > /tmp/temp_key.pem
          chmod 400 /tmp/temp_key.pem

      - name: Make deploy scripts executable
        run: chmod +x docker_*.sh

      - name: Run Deployment Script
        run: ./docker_deploy.sh
